import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "keattz.net",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <header className="container max-w-custom mx-auto px-4 py-4">
          <h1 className="font-bold text-3xl">{metadata.title}</h1>
        </header>
        <main className="container max-w-custom mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
